export function generatePrompt() {
  const promptTypes = [
    "action photograph",
    "professional high angle landscape photograph",
    "90s fish eye photograph",
    "minimalist b&w mid-century geometric poster design",
    "chiaroscuro renaissance painting",
    "low poly render",
    "beautifully lit cubist sculpture",
    "action movie promotional photograph",
    "vintage horror movie poster",
    "80s educational infographic",
    "impressionist watercolor painting",
    "propaganda poster",
    "vintage advertisement",
    "vintage photograph",
    "security footage",
    "vector art illustration",
    "highly detailed manga anime artwork",
    "a cave painting",
    "a children's book illustration",
    "a comic book panel",
    "a comic book cover",
    "a political cartoon",
    "a surrealist painting",
    "a pop art painting",
    "a balloon animal",
    "a balloon sculpture",
    "a plastic toy",
    "a porcelain figurine",
    "a marble statue",
    "a cake",
    "an extreme close up",
    "a macro photograph",
    "a microscopic photograph",
    "a satellite photograph",
    "a selfie",
    "a portrait",
    "a street art mural",
    "fantasy-themed digital art",
    "neoclassical artwork",
    "psychedelic poster",
    "futuristic concept art",
  ];
  let promptSubjects = [
    "a rally car",
    "a beautiful bouquet of flowers",
    "friendly monsters",
    "mist and smoke",
    "explosions",
    "an haute couture model",
    "monkeys",
    "an art director",
    "a cat",
    "palm trees",
    "risotto and broccoli",
    "important business people doing business",
    "a robot",
    "muppets and puppets",
    "a hot air balloon",
    "a luxury watch",
    "a pair of sneakers",
    "an athlete",
    "an angry dragon",
    "a highly detailed spaceship",
    "happy people",
    "dancing people",
    "fighting people",
    "marble statues",
    "modern art",
    "a riot",
    "a revolution",
    "a parade",
    "a wedding",
    "a birthday party",
    "a graduation",
    "a concert",
    "a rave",
    "a festival",
    "a rescue mission",
    "a secret mission",
    "a beautiful model",
    "a mysterious device",
    "controversial art",
  ];
  const promptLocations = [
    "paris fashion week",
    "a rainy amsterdam alley",
    "a museum of modern art",
    "mars",
    "a dimly lit cave",
    "a magical world",
    "a fantasy world",
    "a cyberpunk world",
    "a medieval world",
    "roman monuments in ruins",
    "a brutalist office lobby",
    "an abandoned building",
    "outer space",
    "the bottom of the ocean",
    "underwater",
    "a forest",
    "a desert",
    "a jungle",
    "a swamp",
    "a mountain",
    "a city street",
    "a city rooftop",
    "a city park",
    "a dark techno club in an abandoned warehouse",
    "a moody forest",
    "a city",
    "a mountain landscape",
    "a creative studio office",
    "a dystopian future",
    "a cyberpunk city",
    "the high desert",
    "a tropical island",
    "a white studio backdrop",
    "a snowy mountain",
    "home",
    "an enchanted castle",
    "a bustling marketplace",
    "a serene beach",
    "an interstellar space station",
  ];

  const promptModifiers = [
    "highly detailed.",
    "low poly.",
    "colorful.",
    "black and white.",
    "minimalist.",
    "neon.",
    "dark and moody.",
    "pastel.",
    "surreal.",
    "scary.",
    "happy.",
    "sad.",
    "funny.",
    "serious.",
    "dramatic.",
    "action packed.",
  ];

  const promptCities = [
    "Venice",
    "Paris",
    "Rio de Janeiro",
    "Sydney",
    "Kyoto",
    "Cape Town",
    "Dubai",
    "New York City",
    "Istanbul",
    "Prague",
    "San Francisco",
    "Santorini",
    "Marrakech",
    "Rome",
    "Barcelona",
    "Amsterdam",
    "Hong Kong",
    "Budapest",
    "Florence",
    "Cusco",
    "Lisbon",
    "St. Petersburg",
    "Bangkok",
    "Vienna",
    "Machu Picchu",
    "Bruges",
    "Dubrovnik",
    "Jaipur",
    "Vancouver",
    "Queenstown",
    "Edinburgh",
    "Seville",
    "Havana",
    "Shanghai",
    "Buenos Aires",
    "Jerusalem",
    "Petra",
    "Singapore",
    "Reykjavik",
    "Cartagena",
    "Luang Prabang",
    "Zurich",
    "Venice Beach, Los Angeles",
    "Berlin",
    "Copenhagen",
    "Tallinn",
    "Mumbai",
    "Montreal",
    "Hanoi",
    "Moscow",
    "Cairo",
    "Mexico City",
    "Stockholm",
    "Agra",
    "Fez",
    "Melbourne",
    "Galway",
    "Bath",
    "Athens",
    "Nairobi",
    "Beirut",
  ];

  function sample<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
  }

  // return sample(promptCities);

  return `${sample(promptTypes)} of ${sample(promptSubjects)} at ${sample(
    promptLocations
  )}. ${sample(promptModifiers)}`;
}
