export function generatePrompt() {
  const promptTypes = [
    "action photograph",
    "professional high angle landscape photograph",
    "90s fish eye photograph",
    "minimalist b&w mid-century geometric poster design",
    "chiaroscuro renaissance painting",
    "low poly render",
    "beautifully lit cubist sculpture",
    "action movie promotional photograph",
    "vintage horror movie poster",
    "80s educational infographic",
    "impressionist watercolor painting",
    "propaganda poster",
    "vintage advertisement",
    "vintage photograph",
    "security footage",
    "vector art illustration",
    "highly detailed manga anime artwork",
    "a cave painting",
    "a children's book illustration",
    "a comic book panel",
    "a comic book cover",
    "a political cartoon",
    "a surrealist painting",
    "a pop art painting",
    "a balloon animal",
    "a balloon sculpture",
    "a plastic toy",
    "a porcelain figurine",
    "a cake",
  ];
  const promptSubjects = [
    "a rally car",
    "a beautiful bouquet of colorful flowers",
    "friendly monsters",
    "mist and smoke",
    "explosions",
    "an haute couture model",
    "monkeys",
    "an art director",
    "a cat",
    "palm trees",
    "risotto and broccoli",
    "important business people doing business",
    "a robot",
    "muppets and puppets",
    "a hot air balloon",
    "a luxury watch",
    "a pair of sneakers",
    "an athlete",
    "an angry dragon",
    "a highly detailed spaceship",
    "happy people",
    "dancing people",
    "fighting people",
    "marble statues",
    "modern art",
    "a riot",
    "a revolution",
    "a parade",
    "a wedding",
    "a birthday party",
    "a graduation",
    "a concert",
    "a rave",
    "a festival",
    "a rescue mission",
    "a secret mission",
  ];
  const promptLocations = [
    "paris fashion week",
    "a rainy amsterdam alley",
    "a museum of modern art",
    "mars",
    "a dimly lit cave",
    "a magical world",
    "a brutalist office lobby",
    "an abandoned building",
    "outer space",
    "the bottom of the ocean",
    "underwater",
    "a forest",
    "a desert",
    "a jungle",
    "a swamp",
    "a mountain",
    "a city street",
    "a city rooftop",
    "a city park",
    "a dark techno club in an abandoned warehouse",
    "a moody forest",
    "a city",
    "a mountain landscape",
    "a creative studio office",
    "a dystopian future",
    "a cyberpunk city",
    "the high desert",
    "a tropical island",
    "a white studio backdrop",
    "a snowy mountain",
  ];

  function sample<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
  }
  return `${sample(promptTypes)} of ${sample(promptSubjects)} at ${sample(
    promptLocations
  )}`;
}
